# Site settings
title: Computer Vision in Python
description: >
  Lecture notes on the graduate course Computer Vision in Python @ Universidad Tecnológica de Bolívar

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opi-lab.github.io/computer-vision-python/" # the base hostname & protocol for your site
repo: "computer-vision-python"

#source: /
# destination: /_site/

author:
  fullname: Andres Marrugo
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: agmarrugo
  twitter: agmarrugo
  # disqus: your_disqus_forum_shortname

google_analytics: 'UA-81909010-1'

markdown: kramdown
